config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'dashboard/show'
  root 'dashboard#index'
  
  namespace :api do
    resources :events, only: [:index, :create, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/api/events_controller.rb
module Api
  class EventsController < ApplicationController
    respond_to :json
    
    
    def index
      respond_with Event.all
    end
    
    def create
      event = Event.new(event_params)
      if event.save
        respond_with :api, event, status: :ok, location: api_events_url
      else
        render json: { errors: event.errors.full_messages }, status: :unprocessable_entity
      end
    end
    
    def show
      event = [Event.find(params[:id])]
      respond_with event
    end
    
    private
    
    def event_params
      params.require(:event).permit(:name, :event_date, :description, :place)
    end
    
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/dashboard/index.html.erb
<!-- Index do dashboard Controller -->
<div class="container" ng-controller="EventsCtrl">
  <div class="jumbotron">
    <h1>AngularJS Tutorial</h1>
    <p>by Marcel Vieira <br>
      <small ng-bind="app"></small>
    </p>
    
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'Ver', dashboard_show_path %>
      <input type="text" placeholder="Digite o que deseja buscar..." ng-model="buscador" class="form-control" ng-change="filterEvents(buscador)">
      <table class="table table-dark table-striped">
        <tr>
          <th>Name</th>
          <th>Date</th>
          <th>Description</th>
          <th>Place</th>
        </tr>
        <tr ng-repeat='event in events'>
          <td>{{event.name}}</td>
          <td>{{event.event_date}}</td>
          <td>{{event.description}}</td>
          <td>{{event.place}}</td>
        </tr>
      </table>
       <form class="form-inline" ng-submit="addEvent()">
          <div class="form-group">
            <input type="text" class="form-control" name="name" placeholder="Name" ng-model="event.name" />
          </div>
          <div class="form-group">
            <input type="text" class="form-control" name="place" placeholder="Place" ng-model="event.place" />
          </div>
          <div class="form-group">
            <input type="text" class="form-control" name="event_date" placeholder="Event date" ng-model="event.event_date" />
          </div>
          <div class="form-group">
            <input type="text" class="form-control" name="description" placeholder="Description" ng-model="event.description" />
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary" ng-disabled="!event.name || !event.place || !event.event_date || !event.description">Add</button>
          </div>
      </form>
    </div>
  </div>
</div>

app/views/dashboard/show.html.erb
<!-- Index do dashboard Controller -->
<div class="container" ng-controller="EventsCtrl">
  <div class="jumbotron">
    <h1>AngularJS Tutorial</h1>
    <p>by Marcel Vieira <br>
      <small ng-bind="app"></small>
    </p>
    
  </div>
  <div class="row">
    <div class="col-md-12">
      <input type="text" placeholder="Digite o que deseja buscar..." ng-model="buscador" class="form-control">
      <table class="table table-dark table-striped">
        <tr>
          <th>Name</th>
          <th>Date</th>
          <th>Description</th>
          <th>Place</th>
        </tr>
        <tr ng-repeat='event in eventos'>
          <td>{{event.name}}</td>
          <td>{{event.event_date}}</td>
          <td>{{event.description}}</td>
          <td>{{event.place}}</td>
        </tr>
      </table>
       <form class="form-inline" ng-submit="addEvent(event)">
          <div class="form-group">
            <input type="text" class="form-control" name="name" placeholder="Name" ng-model="event.name" />
          </div>
          <div class="form-group">
            <input type="text" class="form-control" name="place" placeholder="Place" ng-model="event.place" />
          </div>
          <div class="form-group">
            <input type="text" class="form-control" name="event_date" placeholder="Event date" ng-model="event.event_date" />
          </div>
          <div class="form-group">
            <input type="text" class="form-control" name="description" placeholder="Description" ng-model="event.description" />
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary" ng-disabled="!event.name || !event.place || !event.event_date || !event.description">Add</button>
          </div>
      </form>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AngularExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body ng-app="angularExample">
    <%= yield %>
  </body>
</html>